//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvatValidator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvatValidator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie je vyplnený druh kontrolného výkazu!.
        /// </summary>
        internal static string DocumentKindMissing {
            get {
                return ResourceManager.GetString("DocumentKindMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pri spracovaní došlo k nasledujúcej neočakávanej výnimke: .
        /// </summary>
        internal static string ExceptionText {
            get {
                return ResourceManager.GetString("ExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vo vstupnom súbore chýba sekcia &quot;Identifikacia&quot;..
        /// </summary>
        internal static string IdentificationSectionMissing {
            get {
                return ResourceManager.GetString("IdentificationSectionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vstupný súbor sa nenašiel!.
        /// </summary>
        internal static string InputFileDoesntExists {
            get {
                return ResourceManager.GetString("InputFileDoesntExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vo vstupnom súbore chýba sekcia &quot;Obdobie&quot;..
        /// </summary>
        internal static string PeriodSectionMissing {
            get {
                return ResourceManager.GetString("PeriodSectionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vo vstupnom súbore chýba sekcia &quot;Transakcie&quot;..
        /// </summary>
        internal static string TransactionSectionMissing {
            get {
                return ResourceManager.GetString("TransactionSectionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validácia xml voči schéme neprešla!.
        /// </summary>
        internal static string XsdValidationFailed {
            get {
                return ResourceManager.GetString("XsdValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok musí byť aspoň 2014!.
        /// </summary>
        internal static string YearNotValid {
            get {
                return ResourceManager.GetString("YearNotValid", resourceCulture);
            }
        }
    }
}
